export const Banners= [
    {
        id: "b1",
        title: "Mega Grocery Sale",
        subtitle: "Up to 50% OFF on essentials",
        image: "https://images.unsplash.com/photo-1542838132-92c53300491e",
        type: "offer",
        route: "/offers",
        priority: 1,
        isActive: true,
        startDate: "2026-02-01",
        endDate: "2026-02-28",
        backgroundColor: "#E53935",
        textColor: "#FFFFFF",
        campaign: "FEB_MEGA_SALE"
    },
    {
        id: "b2",
        title: "Fresh Fruits & Veggies",
        subtitle: "Farm fresh delivered daily",
        image: "https://images.unsplash.com/photo-1610348725531-843dff563e2c",
        type: "category",
        targetId: "cat_fruits",
        route: "/category/fruits",
        priority: 2,
        isActive: true,
        backgroundColor: "#43A047",
        textColor: "#FFFFFF",
        campaign: "FRESH_WEEK"
    },
    {
        id: "b3",
        title: "Premium Dairy Products",
        subtitle: "Best quality milk & cheese",
        image: "https://images.unsplash.com/photo-1580910051074-3eb694886505",
        type: "category",
        targetId: "cat_dairy",
        route: "/category/dairy",
        priority: 3,
        isActive: true,
        backgroundColor: "#1E88E5",
        textColor: "#FFFFFF",
        campaign: "DAIRY_SPECIAL"
    },
    {
        id: "b4",
        title: "Buy 1 Get 1 Free",
        subtitle: "On selected snacks",
        image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
        type: "offer",
        route: "/offers/bogo",
        priority: 4,
        isActive: true,
        backgroundColor: "#FB8C00",
        textColor: "#FFFFFF",
        campaign: "BOGO_SNACKS"
    },
    {
        id: "b5",
        title: "New Arrivals",
        subtitle: "Latest products just dropped",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        type: "product",
        targetId: "prod_new_collection",
        route: "/products/new",
        priority: 5,
        isActive: true,
        backgroundColor: "#8E24AA",
        textColor: "#FFFFFF",
        campaign: "NEW_LAUNCH"
    },
    {
        id: "b6",
        title: "Electronics Bonanza",
        subtitle: "Top gadgets at best prices",
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
        type: "category",
        targetId: "cat_electronics",
        route: "/category/electronics",
        priority: 6,
        isActive: true,
        backgroundColor: "#3949AB",
        textColor: "#FFFFFF",
        campaign: "TECH_WEEK"
    }
];
